### ISSUE TITLE
what is happening with pokemon bot?

### ISSUE THREAD

**Issue by lomatosiono** [PokeBotPub/PokeBot-Android#107]
Hi, today pokemon bot is not working... and its website not available
someone who knows what happened? :(

**Comment by z55536** [comment]
更新了嗎

**Comment by macinmn** [comment]
dunno, but I think dev got fed up with dumb requests/complaints and entitled users demanding fixes instead of asking nicely.  dev only has incentive to fix things to keep up ad revenues from people launching app.  

PLUS, with some uncertainties relating to safetynet, and new real world client, I think everyone is sitting back until some solid workarounds are released.
