### ISSUE TITLE
New version can have?

### ISSUE THREAD

**Issue by jouni88** [PokeBotPub/PokeBot-Android#132]
Can new version have some kind what can choose what km eggs use 😄👍

**Comment by Ogredou** [comment]
Is your pokebot working ? Coz mine always saying No usable pokestop in your area.

**Comment by jouni88** [comment]
Nope look other comments about that

**Comment by Ogredou** [comment]
ah okay so it means that all the user are having problem that the same as
mine ? the "No usable pokestops in this area"?

On Oct 8, 2016 3:02 PM, "jouni88" <notifications@github.com> wrote:

Nope look other comments about that

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PokeBotPub/PokeBot-Android/issues/132#issuecomment-252408039>,
or mute the thread
