### ISSUE TITLE
Difference between manual and auto solve capcha

### ISSUE THREAD

**Issue by alelast** [PokeBotPub/PokeBot-Android#158]
How works manual mode?

**Comment by PokeBotPub** [comment]
Manual mode : When captcha verification need, you get a notification and phone rinning. You can open application and verify captcha. 

Auto solve mode : You don't need any action. Our servers verify captcha. Full slient.

Actually, i suggest auto solve mode. Because Niantic can be detect bot on manual mode. If your delay to manual captcha verification, its possible.

**Comment by watkinz88** [comment]
Im sure captcha isnt even there any more botted on few accounts today for 6 hours each account straight no capctha normaly get it twice hour anyone confirm this? Also bot doesnt catch many pokemon.

**Comment by BlackAxe8080** [comment]
I can't solve it manually, while i'm selecting the images they disappear....what can I do?
