### ISSUE TITLE
IS THERE A POSSIBILITY OF GETTING BANNED?

### ISSUE THREAD

**Issue by Ajoi1986** [PokeBotPub/PokeBot-Android#272]
Had donated USD10 for the pokekey and now the pokebot v1.0.31 is working back.
Previously I used free version of pokebot v.1.0.30 with manually solving autocaptch on my level 33 poGO account. I run the bot but somehow felt asleep and by the time I woke up my level 33 account had been suspended (permanent banned).
Do we still need to play cautiously even with the pokekey? 
Is there such a thing as a maximum limit for pokemon capture, pokestop spinning, XP grinding in a certain period of time?
If yes, I might bot occasionally only.
One more thing, when I activated the pokekey, it said 'left 735 hours'. Is it referring to the time for botting? Meaning that if I seldomly used it, let's say only using it for 2-3 hours a day, it might last long enough till 735 hours. Am i wrong?

**Comment by ShairaMaex** [comment]
you can check it other isssue m regardingnthat cause i already told them to
limit of bot using. give it a rest for couple of mins. without using it.

On Jan 5, 2017 8:09 AM, "Ajoi1986" <notifications@github.com> wrote:

Had donated USD10 for the pokekey and now the pokebot v1.0.31 is working
back.
Previously I used free version of pokebot v.1.0.30 with manually solving
autocaptch on my level 33 poGO account. I run the bot but somehow felt
asleep and by the time I woke up my level 33 account had been suspended
(permanent banned).
Do we still need to play cautiously even with the pokekey?
Is there such a thing as a maximum limit for pokemon capture, pokestop
spinning, XP grinding in a certain period of time?
If yes, I might bot occasionally only.
One more thing, when I activated the pokekey, it said 'left 735 hours'. Is
it referring to the time for botting? Meaning that if I seldomly used it,
let's say only using it for 2-3 hours a day, it might last long enough till
735 hours. Am i wrong?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PokeBotPub/PokeBot-Android/issues/272>, or mute the
thread

**Comment by Ajoi1986** [comment]
Can you e-mail me the screenshots of the setting?
ahmadfaizul86@gmail.com
thx

**Comment by Mtin096** [comment]
can you send me the screenshots  please?
m.escobar.96@live.com

**Comment by jyce50** [comment]
can you send me the screenshots too please?

marcel19711@outlook.fr
