### ISSUE TITLE
Pls bring back pokebot free version.. Tq

### ISSUE THREAD

**Issue by BangMet** [PokeBotPub/PokeBot-Android#275]
Lot of problem with the keys & facing account ban also..

**Comment by cj3n** [comment]
Why waste your money when you can get permanently ban. This app was better free, they could make their money from ads but got to greedy. 10 bucks a month, like really?

**Comment by aquibzafar** [comment]
Yeah ! Now because of this i am shifting to pc bot . This was risky but was convenient . But pc bots aren't risky though little inconvenient i am shifting to that .

**Comment by ShairaMaex** [comment]
sure, we cant force anybody to shift to paidbots nowadays the bots are
risky. it depends how u use it.

**Comment by cj3n** [comment]
Going to "free"  pc bot fuck 1st  bucks a month what a joke

**Comment by cj3n** [comment]
10 bucks not 1st

**Comment by macinmn** [comment]
they explained why 1.0.31 is paid (0.51.2 costs money to hash with 3rd party, albeit they are charging far more than it costs to pay the hashing side).   If you are using on a PC with emulator, v1.0.30 runs free legacy 0.45 version the same as it has for months, you just need to add the IP it version checks to your firewall block list and it should work.

I would think they were making enough off ads (especially since you had to see them twice as it was, at every single log in start) to make it cost effective to continue, but I don't know the real numbers.   if I cycled through 10 accounts to catch one rare, I loaded 20 ads within the span of 10 minutes.   alternatively, I would think if they force an ad every X minutes or catches, they could work it out.
