### ISSUE TITLE
Pokebot 1.0.32?

### ISSUE THREAD

**Issue by TigerTheDark** [PokeBotPub/PokeBot-Android#297]
Hi guys of pokebot team, first of all thanks for your software it's a great piece of code and I love to use it. 
Now the question, when we will have a updated version of pokebot? since pogo update is mandatory now I'm not using it and I am guessing that a lot of guys are wondering the same.
Thanks again for your software and keep up the good work!

**Comment by ShairaMaex** [comment]
Big Update is Coming so Pokepub are not giving dates when it will release
so far.

this will be changing api. if this big update will ne release and will be
affecting on pokebot. so this will be might take time :)

-ShaireMaeX Unofficial TechSup.

On Jan 20, 2017 9:52 PM, "TigerTheDark" <notifications@github.com> wrote:

Hi guys of pokebot team, first of all thanks for your software it's a great
piece of code and I love to use it.
Now the question, when we will have a updated version of pokebot? since
pogo update is mandatory now I'm not using it and I am guessing that a lot
of guys are wondering the same.
Thanks again for your software and keep up the good work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PokeBotPub/PokeBot-Android/issues/297>, or mute the
thread

**Comment by cj3n** [comment]
With ads and bugs to come for 10 a month.

**Comment by cj3n** [comment]
Free pc bot works better than this: http://necrobot.net/

**Comment by ArthurPetrilli** [comment]
Hi, I need someone to clarify.  Does Pokebot version 1.0.32 use the latest API 0.53.1???  Next questions, If i update, will i be able to use this without getting an invalid pokekey msg??????
