### ISSUE TITLE
Pokebot stopped

### ISSUE THREAD

**Issue by Xeesemaster** [PokeBotPub/PokeBot-Android#337]
Hi, 
I can't login... It says: pokebot stopped... And it shut down. 
Regards

**Comment by Xeesemaster** [comment]
... I mean, when logging on google it says: "sorry, pokebot was interrupted" and shuts down.

**Comment by PokeBotPub** [comment]
Can you try clear cache of application?

**Comment by AbiDez** [comment]
How many times? 
I have crash after 2 minutes work with 1.0.40...
Clear cache, reinstall.... Work for 5 mins... 
Update 1.0.41 same thing.... 
1.0.42.... Works 20 mins... I don't. Know... So I have to clear everything... And set all settings new? 
OMG on every update I test new Acc before I use my own... And since 1.0.40 I have problems, and flags....and a valid Premium 😯

**Comment by ArthurPetrilli** [comment]
Sup!  Since 2 of my 2nd string acct got flagged....let them rest until warning ban goes away.  every time i log in (playing legit) i see the warning ban....this happened to me in December....shit last almost a week....Unless pokebot has an algorithm to address the acknowledged warning ban....don't use those accts for a week.  they will get banned.  I am now using my 1st string accts...
