### ISSUE TITLE
Need Pokebot 1.0.43 ???

### ISSUE THREAD

**Issue by ArthurPetrilli** [PokeBotPub/PokeBot-Android#341]
2 days ago, i ran an acct that has not been used for 2 weeks....level 28.....there was no ban warning when i logged in with normal pogo.   Then yesterday, i logged in with bot for 1 hour.....waited an hour.....logged in normal pogo on same cell phone....."Ban Warning!!!!" I used pokebot 1.0.42.....
Pokebot needs to go back to the drawing board and come out with 1.0.43

**Comment by AbiDez** [comment]
Hi Arthur, it's good to see that we have the same problems... 
Every account is flagged after use the bot atm. 
Lv25 flagged, after use bot 1h flagged... 
Same with Lv27...
And with a flagged account is no login possible in pokebot, because the Captcha... 
So i think I s time to say GB to my lv25&27, like the other accs in the past month....

**Comment by ArthurPetrilli** [comment]
Your acct is not gone yet.....as long as you don't use pokebot again.  I am putting all my old acct in cold storage....when trading opens up....i am moving my best pokemon to a bot-free acct

**Comment by ArthurPetrilli** [comment]
Once i transfer all my good pokemon....i may use those acct again with pokebot when it feels safe

**Comment by PokeBotPub** [comment]
PokeBot 1.0.43 Released!
[B]Version Changes:[/B]

* Crash problem fixed
* More stability works
