### ISSUE TITLE
Is it working now? Is it Save to use?

### ISSUE THREAD

**Issue by KeyzerEX** [PokeBotPub/PokeBot-Android#352]
Hi guys with update 1.0.47 is Pokebot save to use now?

**Comment by ArthurPetrilli** [comment]
why don't you try it....using pokebot is "use at your own risk" Don't get mad if you lose your acct....it is a gamble

**Comment by KeyzerEX** [comment]
Actually before i post this question i already tried it. It is been almost 2 hour now, bot still run, not disconnected from pogo.

**Comment by ArthurPetrilli** [comment]
There are no guarantees.  I lost all my best acct (6) in Jan ban wave.  I lost all my 2nd best acct (6) in February ban wave.  If you are using a bot, be prepared to lose your acct early on....otherwise you will be extremely pist when it catches up with you.  I thought my accts were safe using a paid program.  Lesson learn....botting again.....this time, i am ready to lose my acct at the drop of a hat.....all my acct got the ban warning.....it is a matter of time b4 permaban or....i just stop botting with my best acct and chill.
