### ISSUE TITLE
The simple truth

### ISSUE THREAD

**Issue by DuffyMcGhee** [PokeBotPub/PokeBot-Android#370]
Ok, let's face it.

If you are here, it is because you cheated the game.

A few FACTS.......

1. The rules are clear, "Don't use Bots."  Specifically;  *attempt to access ...Content...through the use of any technology or means other then those provided by Niantic...(including, without limitation, automation software, bots, spiders, crawlers, data-mining tools.....etc)

2. When you paid for the services of Pokebot, they gave you access to their software for a certain number of days, actually it was listed in hours.  And it is just a simple count down timer. So, the fact that any time there is an issue, and the Pokebot team issues us all 2-3 Days extra time, is, in fact, a gift. Because NONE OF US LOST ANYTHING. You still have the same amount of time remaining no matter how long it took them to re-invent the wheel and get their Cheat System back functioning. Just because you don't use the system for 1, 2 5, or 10 days, for whatever reason, you don't lose a single minute of the TIME you paid for. They are not Required to credit us with anything, they do it as a customer service, and I appreciate it.

3.  Niantic has an excellent team of developers, gaming is a Huge business, and they specifically target programs that hack their systems for good reasons. So keep that in mind as you cheat your way to greatness in Pokemon Land. Pokebot is providing us all with a way to cheat, and Niantic can, and will, target them repeatedly, so be prepared for the hammer to fall at any time.

Personally, I appreciate what Pokebot does, it helps me surprise my kids with lots of cool pokemon, items, and game experience on occasion, they love playing. And the old man tries to stay a level ahead, just because, well, Dad has to win!

So, stop whining, grow a pair, and face it, we are all cheaters. Whatever happens to your 47 different accounts and 19 devices is justified, and we all deserve it in the end.

Thanks Pokebot.

Ya'll have a great day.

**Comment by Scribsink** [comment]
But im lost in here.

They give us 3 days extra, but the bot is not running right now right?

Or is it? When will be 2.0.0 released,

**Comment by DuffyMcGhee** [comment]
Yes, they are going to give us 3 days, and yes, the bot has been offline longer then that.

But.....


You didnt lose ANY playing time per your purchase, you still have the 352??? Just throwing a number out, hours you had when it went down.

What the developers are doing is giving us Extrs time for compensation and not being able to play.

**Comment by ShairaMaex** [comment]
I love your speech bro, for the whinnners and all thise who complain.

**Comment by Scribsink** [comment]
Yeah im getting you. But now is says my pokecoin isnt valid. 1hr back it worked good. Still have 640+hrs to go

**Comment by PokeBotPub** [comment]
I love your guys. I added 7 days gift all Pokekeys.

**Comment by Scribsink** [comment]
I love you guyssssss toooo! 7 days!!!! Whoah!

GREAT!!!!!!

**Comment by BangMet** [comment]
New update?

**Comment by OmegaMutant** [comment]
Okay! Great ethics lesson.  What is the point?  You thoughts sound great but your use of fallacious reasoning very obvious.  There is nothing simply about the truth you are preaching.  If it was simple, there would not be soooo much drama in those closed chats.  When people are involved, it is never simple!  People will act irrational and go off the deep end.  Pokebot is still a business.  We pay money to use the program; however, it ain't the only rodeo in town!!!!  Cheaters do not have to stay with pokebot!  If you are unhappy, there are a few other bots that you can pursue.  The question is, which one does a better job?  Which one provides better support?  You give too much credit to Niantic's development team.  Pokemon Go still sucks.  Gym battles tank, there is no PVP, and most of all....no TRADING.  Are you implying that Niantic's programmers are better than pokebot's programmers?  If that is the case, yes....it's it is a matter of time when your accounts get get the AXE....again....we go back to the simple truth.....human emotion will overshadow logic when people end up with terminated accounts if they believe Pokebot's team was negligent with an update.

**Comment by OmegaMutant** [comment]
DuffyMcGhee:
"When you paid for the services of Pokebot, they gave you access to their software for a certain number of days, actually it was listed in hours. And it is just a simple count down timer. So, the fact that any time there is an issue, and the Pokebot team issues us all 2-3 Days extra time, is, in fact, a gift. Because NONE OF US LOST ANYTHING. You still have the same amount of time remaining no matter how long it took them to re-invent the wheel and get their Cheat System back functioning. Just because you don't use the system for 1, 2 5, or 10 days, for whatever reason, you don't lose a single minute of the TIME you paid for. They are not Required to credit us with anything, they do it as a customer service, and I appreciate it."

When i first read this, i knew it was wrong but i needed to collect the pertinent data to share.  After work, i logged in and verified my pokebot hours [screen capture].  I made sure i logged out.  Several hours later, i repeated the steps and it clearly indicates that the timer is ticking down....and i DID NOT even play at all.  I expect you will replicate my investigation and make amendments to your statement.

![pokebot timer 2017 03 29](https://cloud.githubusercontent.com/assets/25358852/24486950/b5e0d32c-14da-11e7-8b15-5963e5354401.jpg)

**Comment by DuffyMcGhee** [comment]
Good catch John,  I stand corrected, and most certainly will amend my statement.
