### ISSUE TITLE
BIG BAN Wave just START

### ISSUE THREAD

**Issue by KingSiq** [PokeBotPub/PokeBot-Android#380]
Better not bot at the moment.

**Comment by OmegaMutant** [comment]
Remember the 3rd party warning issued 3-4 weeks ago? 

Since the warning, any account that apparently has used the bot even once is banned. March 22 was the last time i had bot on the accounts in cold storage.

I have one acct that survived the first ban wave in January still works today because i no longer used the bot on that acct since January's ban wave.

I had even used a clean phone (no pokebot) to log into an account that was in cold storage since March 22 - banned :)

I wonder why Niantic gave everyone that ban warning if they were going to just ban you anyway.  Maybe at the time Niantic was not 100% confident with who was a bot and who was not....apparently they tweaked out the uncertainty factor.
