### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Scribsink** [PokeBotPub/PokeBot-Android#382]
.

**Comment by Scribsink** [comment]
Please delete -

**Comment by OmegaMutant** [comment]
Did you change your mind?
I tried to put your code on my extra device.  Code invalid :)

**Comment by Scribsink** [comment]
No, but its already active on 5 devices.

**Comment by OmegaMutant** [comment]
It feels like pokebot.pub is on its last leg.  
Level up fast or painfully slow, human, does not matter.  
Bot every day
Bot every 3rd day
There must be something that makes pokebot stand out. 
My lv 29 account that survived the January ban is most likely due to being 2ndary, test, account that I used sparingly since botting from October to January.
I used a different bot in Oct-Nov
