### ISSUE TITLE
Key expired before corresponding

### ISSUE THREAD

**Issue by Ger11** [PokeBotPub/PokeBot-Android#383]
My pokekey lost all the time allotted, it was more than 600 hours and to this day I have nothing, please help, you can see that my code was rarely used.

**Comment by OmegaMutant** [comment]
When did you make the payment?  When did the polkekey show up in your email.

When i made a payment, i used the pokekey 2 days later and it indicated that i had 28 days left....time conversion

The timer keeps running down whether you use the bot or not

**Comment by Ger11** [comment]
Any response since pokebot?

**Comment by OmegaMutant** [comment]
It is really quiet in here.  I read,  now closed issue, that someone gave up their pokekey and "Threw in the Towel."

**Comment by ShairaMaex** [comment]
None respond

**Comment by MisterJohnHanke** [comment]
Is pokebot working after the massive ban wave?

**Comment by OmegaMutant** [comment]
When I login, i see "No usable PokeStops found in your area."

Please Wait .....see a red line going in circles

**Comment by OmegaMutant** [comment]
Yeah, it works.
Somehow, Niantic can see which of my accounts use pokebot.  
level up moderately fast, level 30 in 1 month.
If i level up really slow, level 28 in 2 months

whether i bot every day or
bot every 3rd day

somehow, Niantic can identity my accounts that use the bot
i still have one account, level 29, left from January ...still works....never bot again with that account since that time January ban wave....also belongs to my kid :)

**Comment by PokeBotPub** [comment]
Please contact with pokebot2018@gmail.com for billing issues.
