### ISSUE TITLE
3rd party ban warning

### ISSUE THREAD

**Issue by pokepup12** [PokeBotPub/PokeBot-Android#385]
Seems to have started reappearing again today.

Of all the accounts which received this previously all but one were permabanned, even ones which weren't opened again before the next ban wave went. The only one which has survived is the one I started to play legit so it *may* be possible to save your accounts. They could still go later but as yet that's the only way I've found to potentially avoid the chop.

I also find the timing of these things suspect. Ban wave after the water festival, 3rd party warning after the Easter event. It's almost like niantic are allowing bots to run to prop up their own stats for these events then putting the hammer down after they've served their purpose.

**Comment by AbiDez** [comment]
Hi... 
For me I lost all accounts, but one is survive with play legit ^^
Lost my sleeping Accs in last ban wave all have 3rd party warning... Lost account with 3rd party warning but have it bottet with the warning... 
Only one account is still alive, see 3rd party warnings and since I play it legit... No warning again today... For me I don't bot this account... I wish you luck for the future but I think the end days has begun... For me I've found a better solution...
But you're right it's possible to save a flagged account when play legit... But we don't have a guarantee

**Comment by pokepup12** [comment]
Me too. Consolidate what's left and wait for trading!

**Comment by LuciferHawk** [comment]
Last month, 3 of my accounts got the 3rd party flag.  I had stopped botting with those.  I would log in everyday to collect daily rewards from pokestop and catching pokemon.   I still lost those accounts.

This month, I had opened several accounts for the purpose of sniping High 100% IV pokemon.  I only ran the bot one time per day.....half of those acct now have 3rd party warning.  I barely ran the bot for 5 minutes.

I have an account has not used bot in 4 days.  Still havegot 3rd party flag.  Yesterday, Niantic made changes....Niantic is trying to catch spoofers now

Common denominator with all my spoof accts......any acct that caught a dratini, dragonair, or dragonite with 98-100% IV got the 3rd party flag.

My other spoof acct that did not get said pokemon do not have 3rd party flag
I hope they open up trading so i can transfer all my 100% IV pokemon to my best account.
