### ISSUE TITLE
Transfer list

### ISSUE THREAD

**Issue by mbtrading88** [PokeBotPub/PokeBot-Android#64]
Crash again with this 1.0.14 patch
Test and fix pls.. tq

**Comment by mbtrading228** [comment]
1.0.15 transfer list setting
Keep Pokemon (add whatever u want to keep it won't delete)
Save after adding then back to minimum Pokemon don't press save.
Back to the menu. 

Transfer list (add Pokemon whatever you want and adjust the min CP) save again after adding then back to minimum and DON'T PRESS SAVE. Back again to menu .. come in and adjust min  Pokemon you want to keep .. 5 if possible. Then only SAVE there.
Once your Pokemon reach 5 it will transfer any one of your pokemon below the minimum CP that you set in transfer list.

This I already try 3 id since this patch . .. remember to check it pokemon bag is full to avoid any ******

**Comment by mbtrading228** [comment]
1.0.15 transfer list setting
Keep Pokemon (add whatever u want to keep it won't delete)
Save after adding then back to minimum Pokemon don't press save.
Back to the menu. 

Transfer list (add Pokemon whatever you want and adjust the min CP) save again after adding then back to minimum and DON'T PRESS SAVE. Back again to menu .. come in and adjust min  Pokemon you want to keep .. 5 if possible. Then only SAVE there.
Once your Pokemon reach 5 it will transfer any one of your pokemon below the minimum CP that you set in transfer list.

This I already try 3 id since this patch . .. remember to check it pokemon bag is full to avoid any ******
